version: '3.9'

volumes:
  app-vol:
  node-modules-vol:
  mongodb-vol:

networks:
  node-template-network:
    name: node-template-network

services:
  base: &base
    hostname: base
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node-modules-vol:/usr/src/app/node_modules
    networks:
      - node-template-network

  app:
    <<: *base
    hostname: app
    image: node-template
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env.local
    ports:
      - 2024:2024
    command: "pnpm run dev"
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    hostname: mongodb
    image: bitnami/mongodb:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-vol:/data/db
    environment:
      MONGODB_EXTRA_FLAGS: "--quiet"
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: primary
      MONGODB_DATABASE: node-template-db-dev
      MONGODB_ROOT_PASSWORD: root
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
    networks:
      - node-template-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
